<script setup>
useHead({
  title: "About",
});
definePageMeta({
  layout: "landing",
  colorMode:"light",  
});


import feature1 from '../assets/img/feature-1.jpg';
import feature2 from '../assets/img/feature-2.jpg';
import feature3 from '../assets/img/feature-3.avif';

const team = [
  {
    name: "Stretching",
    title: "Stretching is a form of physical exercise in which a specific muscle or tendon is deliberately flexed or stretched in order to improve the muscle's felt elasticity and achieve comfortable muscle tone.",
    avatar: {
      src: feature1,
    },
  },
  {
    name: "Wheight exercises",
    title: "Weight training is a common type of strength training for developing the strength and size of skeletal muscles. It utilizes the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose the force generated by muscle through concentric or eccentric contraction.",
    avatar: {
      src: feature2,
    },
  },
  {
    name: "Join the Community",
    title: "Become a part of our community and get support and motivation from other members.",
    avatar: {
      src: feature3,
    },
  },
];
</script>

<template>
  <LandingContainer>
    <LandingSectionhead>
      <template v-slot:title>About</template>
      <template v-slot:desc>We are <span class="text-red-800">Easy</span>Exercises</template>
    </LandingSectionhead>
   

    <div class="flex flex-col gap-3 mx-auto max-w-4xl mt-14 lg:pt-16">
      <h2 class="font-bold text-3xl text-gray-800">
        Empowering Your Fitness Journey with Our Platform.
      </h2>
      <p class="text-lg leading-relaxed text-slate-500">
        Our platform is designed to help individuals around the world reach their fitness goals. We provide detailed exercise instructions, customizable workout plans, and a supportive community to keep you motivated. No matter your fitness level or experience, our platform has the tools and resources to help you succeed on your fitness journey..
      </p>
    </div>
    <div class="grid md:grid-cols-3 gap-10 mx-auto max-w-4xl mt-12">
      <div v-for="item of team" class="group">
        <div class="w-full aspect-square">
          <img
            :src="item.avatar.src"
            :width="item.avatar.width"
            :height="item.avatar.height"
            format="avif"
            alt="Exercise team member avatar"
            class="h-[280px] w-[400px] object-cover rounded transition group-hover:-translate-y-1 group-hover:shadow-xl"
          />
        </div>

        <div class="mt-4 text-center">
          <h2 class="text-lg text-gray-800">{{ item.name }}</h2>
          <h3 class="text-sm text-slate-500">{{ item.title }}</h3>
        </div>
      </div>
    </div>
    <LandingFeatures></LandingFeatures>
  </LandingContainer>
</template>
